In [2]:
import json
from tqdm import tqdm

## 处理数据集

处理交互信息

In [4]:
file = "D:\work_space\Health_and_Personal_Care.jsonl"
with open(file, 'r') as fp:
    for line in tqdm(fp):
        data = json.loads(line.strip())
        user_id = data['user_id']
        asin = data['asin'] 
        rating = data['rating']
        timestamp = data['timestamp']

        with open('D:/Code/graduation_design/data/Health_and_Personal_Care/interaction.dat', 'a') as f:
            f.write(f"{user_id}::{asin}::{rating}::{timestamp}\n")

494121it [02:25, 3399.12it/s]

处理物品信息

In [8]:
file = "D:\Code\graduation_design\data\magzine\meta_Magazine_Subscriptions.jsonl"
with open(file, 'r') as fp:
    for line in tqdm(fp):
        data = json.loads(line.strip())
        parent_asin = data['parent_asin']
        with open('D:/Code/graduation_design/data/magzine/item.dat', 'a') as f:
            f.write(f"{parent_asin}::{json.dumps(data)}\n")

3391it [00:00, 3914.72it/s]

## 验证数据集

In [2]:
import pandas as pd
data = pd.read_csv("D:/Code/graduation_design/data/Health_and_Personal_Care/interaction.dat", sep="::", header=None, engine='python')
data.columns = ['user', 'item', 'rating', 'timestamp']
data

                                user        item  rating      timestamp
0       AFKZENTNBQ7A7V7UXW5JJI6UGRYQ  B07TDSJZMR     4.0  1580950175902
1       AEVWAM3YWN5URJVJIZZ6XPD2MKIA  B08637FWWF     5.0  1604354586880
2       AHSPLDNW5OOUK2PLH7GXLACFBZNQ  B07KJVGNN5     5.0  1563966838905
3       AEZGPLOYTSAPR3DHZKKXEFPAXUAA  B007HY7GC2     4.0  1662258542725
4       AEQAYV7RXZEBXMQIQPL6KCT2CFWQ  B08KYJLF5T     1.0  1642722787262
...                              ...         ...     ...            ...
494116  AEQG5UEVYBNLWPXB3E2EODQ3EGSQ  B07KXT7Y48     5.0  1555042864257
494117  AGTVLNJAFZTKURBCHLUIH6VEOQCQ  B07KXT7Y48     5.0  1594962099190
494118  AGMA5UN3JPLQLQZ2PFYHJYSC4PNA  B07KXT7Y48     5.0  1551998016968
494119  AE2Q3FXHIVGSSDGTNI4YLXDXMCIA  B07KXT7Y48     5.0  1569500571244
494120  AH5K35CHSUC2QMGRMDQNXR6BJ72A  B07JYKP19X     5.0  1570064639311

[494121 rows x 4 columns]

In [3]:
data = data[data['rating'] > 2]

# 过滤交互次数少于阈值的用户和物品
user_counts = data['user'].value_counts()
item_counts = data['item'].value_counts()

users_to_keep = user_counts[user_counts >= 10].index
items_to_keep = item_counts[item_counts >= 10].index

data = data[data['user'].isin(users_to_keep)]
data = data[data['item'].isin(items_to_keep)]

# 查看用户数量
n_users = len(data['user'].unique())
print(f"用户数量: {n_users}")

data = data.sort_values(['user', 'timestamp'])
data = data.reset_index(drop=True)
data.head()

用户数量: 184

                           user        item  rating      timestamp
0  AE23ZBUF2YVBQPH2NN6F5XSA3QYQ  B08D93ZSWY     5.0  1617386156739
1  AE23ZBUF2YVBQPH2NN6F5XSA3QYQ  B08Z474Q6J     4.0  1623006699731
2  AE23ZBUF2YVBQPH2NN6F5XSA3QYQ  B098WFX6TY     5.0  1633210886052
3  AE23ZBUF2YVBQPH2NN6F5XSA3QYQ  B093ZTWFGP     5.0  1637202836681
4  AE23ZBUF2YVBQPH2NN6F5XSA3QYQ  B09VCSTX43     5.0  1651929665448

In [5]:
data

                                 user        item  rating      timestamp
0        AE223J6LBWPONMIKQGHAI3X5GNOQ  B00KH3YC6S     4.0  1452983982000
1        AE223J6LBWPONMIKQGHAI3X5GNOQ  B00PSLJXEU     4.0  1454001753000
2        AE223J6LBWPONMIKQGHAI3X5GNOQ  B00YFT082W     4.0  1454452984000
3        AE223J6LBWPONMIKQGHAI3X5GNOQ  B003PPCSTI     5.0  1457657199000
4        AE223J6LBWPONMIKQGHAI3X5GNOQ  B004NIFOHE     4.0  1458993870000
...                               ...         ...     ...            ...
4701070  AHZZZ6UASY7CGOTGP5BH5637FMPA  B000FCK2VK     5.0  1559586410781
4701071  AHZZZ6UASY7CGOTGP5BH5637FMPA  B01ARGAGUU     4.0  1561402127023
4701072  AHZZZ6UASY7CGOTGP5BH5637FMPA  B078JDQ9BH     4.0  1565362465964
4701073  AHZZZ6UASY7CGOTGP5BH5637FMPA  B06ZZLH321     4.0  1568731587933
4701074  AHZZZ6UASY7CGOTGP5BH5637FMPA  B01HBKAYMA     4.0  1578763768769

[4701075 rows x 4 columns]